import api from './axios'
export const getDashboardStats = () => api.get('/admin/dashboard')
export const getUsers = () => api.get('/admin/users')
export const createUser = (data) => api.post('/admin/users', data)
export const updateUser = (id, data) => api.put(`/admin/users/${id}`, data)
export const updatePermissions = (id, data) => api.put(`/admin/users/${id}/permissions`, data)
export const resetUserPassword = (id, data) => api.put(`/admin/users/${id}/reset-password`, data)
export const toggleUserStatus = (id) => api.put(`/admin/users/${id}/toggle-status`)
export const deleteUser = (id) => api.delete(`/admin/users/${id}`)
export const getSettings = (params) => api.get('/admin/settings', { params })
export const createSetting = (data) => api.post('/admin/settings', data)
export const updateSetting = (id, data) => api.put(`/admin/settings/${id}`, data)
export const deleteSetting = (id) => api.delete(`/admin/settings/${id}`)
export const addSettingValue = (id, data) => api.post(`/admin/settings/${id}/values`, data)
export const removeSettingValue = (id, valueId) => api.delete(`/admin/settings/${id}/values/${valueId}`)
