import api from './axios'
export const getTransactions = (params) => api.get('/finance/transactions', { params })
export const createTransaction = (data) => api.post('/finance/transactions', data)
export const updateTransaction = (id, data) => api.put(`/finance/transactions/${id}`, data)
export const deleteTransaction = (id) => api.delete(`/finance/transactions/${id}`)
export const getFinanceSummary = (params) => api.get('/finance/summary', { params })
export const getInvestments = () => api.get('/finance/investments')
export const createInvestment = (data) => api.post('/finance/investments', data)
export const updateInvestment = (id, data) => api.put(`/finance/investments/${id}`, data)
export const deleteInvestment = (id) => api.delete(`/finance/investments/${id}`)
export const getTaxDeductions = (params) => api.get('/finance/tax-deductions', { params })
export const createTaxDeduction = (data) => api.post('/finance/tax-deductions', data)
export const updateTaxDeduction = (id, data) => api.put(`/finance/tax-deductions/${id}`, data)
export const deleteTaxDeduction = (id) => api.delete(`/finance/tax-deductions/${id}`)
export const getNetWorth = () => api.get('/finance/networth')
